# Use Python 3.12.3 as the base image
FROM python:3.12.3

# Set the working directory in the container
WORKDIR /usr/src/program
COPY . /usr/src/program/

# Copy the requirements.txt file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt



# Command to run the ML project (assuming app.py is the entry point)
CMD ["python", "app.py"]
