# Use an official Python runtime as a parent image
FROM python:3.12.3

# Set the working directory in the container
WORKDIR /app

# Copy the setup.py and requirements.txt files to the working directory
COPY setup.py ./
COPY requirements.txt ./

# Install the project dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install the package itself
RUN pip install --no-cache-dir .

# Copy the rest of the application code to the working directory
COPY . .

# Expose any ports your application needs (adjust as necessary)
EXPOSE 8000

# Command to run your application or scripts
CMD ["python", "app.py"]
